---
id: add_company_to_crm
name: add_company_to_crm
description: Adds a new company to amo CRM
response-description: "Boolean value: true if the company added to amo CRM successfully,\
  \ false if not"
parameters:
- name: name
  type: STRING
  required: false
  description: name of the company
  properties: null
  items: null
